name: Deploy Hugo site to GitHub Pages


permissions:
  contents: write
  pages: write
  id-token: write

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - gh_pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.126.1'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
